s = 'CTTTCGCTCCACAGAGGGGCCCTCCTTGTGGGACAGAATAGAGCCCCAGCTGCCAGATGCTCAAGTGACCCCCAGGTTTCTACCATTTGCAGGCGGTAGGGCAGTAAATAACCCCTCTCACTTAACTCAGAAGTGACGACGTTAGTTGACGAGATCTGTGCCAGTGACCTCGCATGCGTCTTCATTCGTACGAAGCCATACCTGTATTTTGAGCATCATGTAGCAAATGGTCTCAGCTCCTCCTTTGTACTCTAGTCCACGGGAATATCCGCCGCGCATTTGTTAAAAAATCTCACCAATCTCGTCCGAGGGTGAGTGTATGCTCTTACTATCGAGCATTGTGCGCTGGTAGTTGTTACGAGATCATAAAAGCCCGAGAGCTCGAGCGCATAATCGTGGTACAACACCGTTAATCTTCTTAGGACCTAGGACCAGGTCGAGCTCCTTTTTGGTAGCTGCCTTTCCAAGCCCGGTCTCATTCTCGAGGTGCACGCTACCGCGTGCTCCAGGGGAGATTCACATCAAGCGCTCGTGATGAATTCGATAATAGAGAGGCGCTAAAGACTAGCCCCGCAAAATTCTCGAGGCGGGACACCCTGTAGACCTTTAGTGGGTGGAGAATAAAGTACTCCCACTTGAACATGTGTTACAACTTCTAAAGAAGCACTCCGTAAGATAACAAGCGGATGGGAGGTACACGCCTCAGTCACTCATCCGTACCGCGCCGCTCGTTGGGCATTGGACTCGAGCCATGCAGCGGGCTTTTGTATTCCGAACGGATGGACACCGCAAAAGTAGTTCTGGGTGGGAGAGTGTTGTATTTCAACGCCGGACTGGTCTTAGATACCGATTAGGGGGGTTTACGGGCATGTCAAGCCACGAGGAACTACTGAATGAACTTGCG      '
d = {}
for c in s:
    if c in d:   
         d[c] = d[c] + 1
    else:
        d[c] = 1
print(d['A'], d['C'], d['G'], d['T'])