s = 'CTTTTCCGAAAACCAAATTCAAGCCTATCAATCTACGGGATAAGTAGCTGTATAGAGAATCATGCCGTGGACTCCTCGGCATGCCAATTGTAGTTCTGGCCCGAGTCGCGAATTTTGCGTAACCCTAGCGCGGACTTGCGCGCCGCTAAGGATCTGCGGGCTGAAGACTGGGGCCGCCAGTCCGCAGTATGCCAGCGACTTCTTAATGTTCGCGTAGAGTGCCGGCTACAACGCATGCGCTCTATCCGACTGCTCAACCGTTCTGTACAGTTTTGTTACTAGAGTGCATCGGCGTCTTCGGAACATGCGTCCACACGGGACTGTAGAGCGCTATCCCAGGATAACTGGTTTTTACTTTATCAGGGCGCCAGCCTTTGTTGCGTTATGTTGAAACCCGCGGTCGCAATGCGATTCTTACGTTTGATGTTCCAAACCGCTAATCCTCAATTGATCACCGCGGCCACGAGCCCCTTAACGATAATAGGAACGGCTAGGGTCATCCAAACGATGCATTGAGAAGGCTGGCCCCGGGTTACCTAATAAGCCGTTTCGCCGTTAGTGTTACACAGCATCGTGTAGTTGACGCTACGATTGGGTAGGGTCTCAATTCGGATGACGTAATACCCACGCTGGCCTACTGATATCTCTAGCAAAAGGGGAGGAGACACATTCCTAACTTCATAGTACGTCAAAGAAAGCCACACGTCTTACTCGCTGGAGGGCTACTAATCCCGATCAGTAGCCACAGACAGCCCCTCCCTCTCAAGTGCTGTGGAGAAGTTCAACCGAACCGTTAAACTGGTCGGTCGTCGGTACTCGGACTGCTTGTTTTAAACCTCGTGTACGTAGGGCCTACCTTGGAGTACCTCCAAACCGTCTGTAGGGTTAGGATAGATATGTTTGGCCTCTGTTTCCGCTATGTTCACGCGACCGCAGGCCAC' 
#s is coding strand
s1 = ''
f = open('output.OUT', 'w')
for c in s:
    if c == 'A':
        c = 'T'
    elif c == 'T':
        c = 'A'
    elif c == 'G':
        c = 'C'
    else :
        c = 'G'
    s1 += c
print(s1[::-1])
f.write(s1[::-1])
f.close()